version: "3.7"
networks:
    test_net:
      ipam:
        driver: default
        config:
          - subnet: 10.0.0.0/24
services:
  ui:
    build:
      context: ../../
      dockerfile: devops/dockerfiles/polkadot-ui/Dockerfile
    ports:
      - 3000:3000
    networks:
        test_net:
          ipv4_address: 10.0.0.10