"use strict";
exports.__esModule = true;
exports.BIG_TRILLION = exports.BIG_HUNDRED_BILLIONS = exports.BIG_TEN_BILLIONS = exports.BIG_BILLION = exports.BIG_HUNDRED_MILLIONS = exports.BIG_TEN_MILLIONS = exports.BIG_MILLION = exports.BIG_HUNDRED_THOUSAND = exports.BIG_TEN_THOUSAND = exports.BIG_THOUSAND = exports.BIG_HUNDRED = exports.BIG_TEN = exports.BIG_ONE = exports.BIG_ZERO = void 0;
var big_js_1 = require("big.js");
exports.BIG_ZERO = (0, big_js_1["default"])("0");
exports.BIG_ONE = (0, big_js_1["default"])("1");
exports.BIG_TEN = (0, big_js_1["default"])("10");
exports.BIG_HUNDRED = (0, big_js_1["default"])("100");
exports.BIG_THOUSAND = (0, big_js_1["default"])("1000");
exports.BIG_TEN_THOUSAND = (0, big_js_1["default"])("10000");
exports.BIG_HUNDRED_THOUSAND = (0, big_js_1["default"])("100000");
exports.BIG_MILLION = (0, big_js_1["default"])("1000000");
exports.BIG_TEN_MILLIONS = (0, big_js_1["default"])("10000000");
exports.BIG_HUNDRED_MILLIONS = (0, big_js_1["default"])("100000000");
exports.BIG_BILLION = (0, big_js_1["default"])("1000000000");
exports.BIG_TEN_BILLIONS = (0, big_js_1["default"])("10000000000");
exports.BIG_HUNDRED_BILLIONS = (0, big_js_1["default"])("100000000000");
exports.BIG_TRILLION = (0, big_js_1["default"])("1000000000000");
