"use strict";
exports.__esModule = true;
exports.BN_DIV_NUMERATOR_MULTIPLIER = exports.BN_DIV_NUMERATOR_MULTIPLIER_DECIMALS = exports.BN_TRILLION = exports.BN_HUNDRED_BILLIONS = exports.BN_TEN_BILLIONS = exports.BN_BILLION = exports.BN_HUNDRED_MILLIONS = exports.BN_TEN_MILLIONS = exports.BN_MILLION = exports.BN_HUNDRED_THOUSAND = exports.BN_TEN_THOUSAND = exports.BN_THOUSAND = exports.BN_HUNDRED = exports.BN_TEN = exports.BN_ONE = exports.BN_ZERO = void 0;
var util_1 = require("@polkadot/util");
exports.BN_ZERO = new util_1.BN("0");
exports.BN_ONE = new util_1.BN("1");
exports.BN_TEN = new util_1.BN("10");
exports.BN_HUNDRED = new util_1.BN("100");
exports.BN_THOUSAND = new util_1.BN("1000");
exports.BN_TEN_THOUSAND = new util_1.BN("10000");
exports.BN_HUNDRED_THOUSAND = new util_1.BN("100000");
exports.BN_MILLION = new util_1.BN("1000000");
exports.BN_TEN_MILLIONS = new util_1.BN("10000000");
exports.BN_HUNDRED_MILLIONS = new util_1.BN("100000000");
exports.BN_BILLION = new util_1.BN("1000000000");
exports.BN_TEN_BILLIONS = new util_1.BN("10000000000");
exports.BN_HUNDRED_BILLIONS = new util_1.BN("100000000000");
exports.BN_TRILLION = new util_1.BN("1000000000000");
exports.BN_DIV_NUMERATOR_MULTIPLIER_DECIMALS = 18;
exports.BN_DIV_NUMERATOR_MULTIPLIER = new util_1.BN("10").pow(new util_1.BN(exports.BN_DIV_NUMERATOR_MULTIPLIER_DECIMALS));
