name: CI
on: [push]
jobs:
  build:
    name: Test code quality and run tests
    runs-on: ubuntu-latest

    env:
      API_URL: 'ws://172.16.238.10:9944'
      TEST_PALLET_ADDRESS: ${{ secrets.TEST_PALLET_ADDRESS }}
      TEST_SUDO_NAME: ${{ secrets.TEST_SUDO_NAME }}

    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn --network-timeout 100000

      - name: Lint
        run: yarn eslint

      - name: Start mangata-node node
        run: docker-compose -f devops/dockerfiles/docker-compose.yml up -d

      - name: Docker ps
        run: docker ps

      - name: Test
        run: yarn test
