name: Release

on:
  push:
    branches:
      - "release/**"

env:
  SKIP_HUSKY: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node version and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the SDK
        run: npm run build

      - name: create release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.FE_TOKEN }}
